# Generated by Django 4.2.8 on 2026-01-31 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='providers/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('office_hours', models.JSONField(blank=True, default=dict, help_text='Office hours as JSON')),
                ('profile_slug', models.SlugField(unique=True)),
                ('languages', models.CharField(blank=True, help_text='Comma-separated language list', max_length=300)),
                ('education', models.TextField(blank=True)),
                ('certifications', models.TextField(blank=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locations', models.ManyToManyField(related_name='providers', to='core.location')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='core.specialty')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['is_active', '-is_featured'], name='providers_p_is_acti_0d9145_idx'), models.Index(fields=['specialty'], name='providers_p_special_47932a_idx')],
            },
        ),
    ]
