# Generated by Django 4.2.8 on 2026-06-18 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Team or department name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Team description and overview')),
                ('photo', models.ImageField(blank=True, help_text='Team group photo', upload_to='teams/')),
                ('order', models.IntegerField(default=0, help_text='Display order on providers page')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['team__order', 'team__name', 'order', 'last_name', 'first_name'], 'verbose_name': 'Provider', 'verbose_name_plural': 'Providers'},
        ),
        migrations.AddField(
            model_name='provider',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order within team'),
        ),
        migrations.AddField(
            model_name='provider',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team or department this provider belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers', to='providers.team'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['team', 'is_active'], name='providers_p_team_id_d5d31b_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['is_active', 'order'], name='providers_t_is_acti_656352_idx'),
        ),
    ]
