# Generated by Django 4.2.8 on 2026-06-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('providers', '0002_team_alter_provider_options_provider_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='locations',
            field=models.ManyToManyField(blank=True, null=True, related_name='providers', to='core.location'),
        ),
    ]
