# Generated by Django 4.2.8 on 2026-06-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_alter_provider_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='position',
            field=models.CharField(blank=True, help_text='Position or role of the team within the organization', max_length=200),
        ),
        migrations.AlterField(
            model_name='provider',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
