# Generated by Django 4.2.8 on 2026-02-01 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(db_index=True, help_text='Unique file number for this patient', max_length=50, unique=True)),
                ('patient_type', models.CharField(choices=[('regular', 'Regular'), ('emergency', 'Emergency'), ('direct_billing', 'Direct Billing')], default='regular', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('national_id_no', models.CharField(blank=True, help_text='National ID Number', max_length=50, null=True)),
                ('passport_no', models.CharField(blank=True, help_text='Passport Number', max_length=50, null=True)),
                ('has_health_insurance', models.BooleanField(default=False)),
                ('insurance_company', models.CharField(blank=True, help_text='Name of insurance company', max_length=150, null=True)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[+]?[0-9\\s\\-()]+$', 'Enter a valid phone number')])),
                ('present_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[+]?[0-9\\s\\-()]+$', 'Enter a valid phone number')])),
                ('email', models.EmailField(max_length=254)),
                ('how_hear_about_us', models.CharField(choices=[('search_engine', 'Search Engine'), ('social_media', 'Social Media'), ('referred_by_friend', 'Referred By Friend'), ('outreach', 'Outreach'), ('others', 'Others')], help_text='How did you hear about us?', max_length=50)),
                ('terms_acknowledged', models.BooleanField(default=False, help_text='Patient acknowledges terms and conditions')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Patient Registration',
                'verbose_name_plural': 'Patient Registrations',
                'ordering': ['-registration_date'],
                'indexes': [models.Index(fields=['file_number'], name='patients_pa_file_nu_43f133_idx'), models.Index(fields=['email'], name='patients_pa_email_32b923_idx'), models.Index(fields=['phone'], name='patients_pa_phone_a81655_idx'), models.Index(fields=['registration_date'], name='patients_pa_registr_519110_idx')],
            },
        ),
    ]
