# Generated by Django 4.2.8 on 2026-01-31 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='HTML content allowed')),
                ('template_name', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('services', 'Services'), ('providers', 'Providers'), ('contact', 'Contact'), ('default', 'Default')], default='default', max_length=50)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title tag', max_length=200)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=300)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords', max_length=300)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL for SEO')),
                ('is_published', models.BooleanField(default=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='pages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pages', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['-updated_at'],
            },
        ),
    ]
